CREATE TABLE [dbo].[Table]
(
	[FIRSTNAME] NVARCHAR(50) NOT NULL , 
    [SECONDNAME] NVARCHAR(50) NOT NULL, 
    [ID] INT NOT NULL, 
    [GENDER] NCHAR(10) NOT NULL, 
    [BIRTHDATE] NCHAR(10) NULL, 
    [EMAIL] NCHAR(10) NOT NULL, 
    [PHONENUMBER] NCHAR(10) NOT NULL, 
    [ADDRESS] NCHAR(10) NOT NULL, 
    [PASSWORD] NCHAR(10) NOT NULL, 
    [NATIONALITY] NCHAR(10) NOT NULL, 
    [FACULITY] NVARCHAR(50) NOT NULL, 
    [BUSS] NCHAR(10) NULL, 
    CONSTRAINT [PK_Table] PRIMARY KEY ([ID])
)
